spring:
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848

  application:
    name: gulimall-search
  #disable thymeleaf cache for dev only
  thymeleaf:
    cache: false

server:
  port: 13000

